version:  '2'
services:
  master:
    image: cluster-zookeeper
    container_name: zk-master
    networks:
      default:
        ipv4_address: 172.17.0.2
    extra_hosts:
      - "slave1:172.17.0.3"
      - "slave2:172.17.0.4"
    hostname: master
    environment:
      ZK_ID: 1
    tty: true

  slave1:
    image: cluster-zookeeper
    container_name: zk-slave1
    networks:
      default:
        ipv4_address: 172.17.0.3
    extra_hosts:
      - "master:172.17.0.2"
      - "slave2:172.17.0.4"
    hostname: slave1
    environment:
      ZK_ID: 2
    tty: true

  slave2:
    image: cluster-zookeeper
    container_name: zk-slave2
    networks:
      default:
        ipv4_address: 172.17.0.4
    extra_hosts:
      - "master:172.17.0.2"
      - "slave1:172.17.0.3"
    hostname: slave2
    environment:
      ZK_ID: 3
    tty: true

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.17.0.0/17


